[package]
name = "life-plus"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/PedroHBrasil/life-plus"

[dependencies]
rand = "0.8.5"
serde = { version = "1.0.*", features = ["derive"] }
speedy2d = "1.12.0"
toml = "0.8.2"
